version: "3.9"

networks:
  zepto_net:
    driver: bridge

volumes:
  cassandra_data:
  auxdb_data:

services:

  auxdb:
    image: postgres:15
    container_name: zepto_auxdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: auxdb
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5446:5432"
    volumes:
      - auxdb_data:/var/lib/postgresql/data
    networks:
      - zepto_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d auxdb"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  kafka:
    image: apache/kafka:3.9.0
    container_name: zepto_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_LOG_RETENTION_HOURS: "168"
    networks:
      - zepto_net
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  cassandra:
    image: cassandra:4.1
    container_name: zepto_cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: zepto-cluster
      CASSANDRA_DC: dc1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_BROADCAST_RPC_ADDRESS: 127.0.0.1
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - zepto_net
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 60s
